apiVersion: v1
kind: Service
metadata:
  name: redis-mastar-svc
  labels:
    app: redis
    role: mastar
    tier: backend
spec:
  selector:
    app: redis
    role: mastar
    tier: backend
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP
